### ISSUE TITLE
AndroidManifest merge problem

### ISSUE THREAD

**Issue by Cromir** [dommerq/SuperListview#20]
Hi guys,
thank you for this wonderful lib.

Including this lib in my project cause app icon changes to default Android robot instead my app icon. I think you should remove the two lines from AndroidManifest from application tag or I have to change something?

<application android:allowBackup="true"
        
        
</application>

Thanks,
Giulio

**Comment by naushad-madakiya** [comment]
Its still creating a problem
I think they have not removed ic_launcher drawable
